###
GET http://localhost:4004/odata/v4/amazon-web-services/Books

###
POST http://localhost:4004/odata/v4/amazon-web-services/Books
Content-Type: application/json

{
    "book_id": "4",
    "book_name": "GOT"
}

###
POST http://localhost:4004/odata/v4/amazon-web-services/BooksAndAuthors
Content-Type: application/json

{
    "book_id": "1"
}

###
PATCH http://localhost:4004/odata/v4/amazon-web-services/Books/3
Content-Type: application/json

{
    "book_name": "Harry Potter"
}

###
DELETE http://localhost:4004/odata/v4/amazon-web-services/Books/3